name: needls_release
on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: install setuptools wheel
        run: python -m pip install setuptools wheel
      - name: setuptools build sdist bdist_wheel
        run: python setup.py build sdist bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: setup_build
          path: dist/

  # Test-PyPi release
  publish_test:
    name: Pusblish on TestPyPi
    runs-on: ubuntu-latest
    needs: build
    env: 
      TWINE_USERNAME : ${{ secrets.TEST_PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/download-artifact@v2
        with:
          name: setup_build
          path: dist/
      - name: Display structure of downloaded files
        run: ls -R
      - name: install twine
        run: python -m pip install twine
      - name: check packages
        run: twine check dist/*
      - name: upload packages to Test PyPi
        # username == token from env, password must be set but empty
        run: twine upload --password "" --repository testpypi dist/*


  # Get calls only, if publish on Test-PyPi has worked.
  publish_oficial:
    name: Pusblish on PyPi
    runs-on: ubuntu-latest
    needs: publish_test
    env: 
      TWINE_USERNAME : ${{ secrets.PYPI_TOKEN }}
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/download-artifact@v2
        with:
          name: setup_build
          path: dist/
      - name: Display structure of downloaded files
        run: ls -R
      - name: install twine
        run: python -m pip install twine
      - name: check packages
        run: twine check dist/*
      - name: upload packages to PyPi
        # username == token from env, password must be set but empty
        run: twine upload --password "" dist/*