# From: https://github.com/rkdarst/sphinx-actions-test/blob/master/.github/workflows/sphinx-build.yml

name: vsce
on:
  push:
    branches:
      - main
  pull_request:

env:
  DEFAULT_BRANCH: "master"
  GITUHB_TOKEN: ${{ secrets.OPEN_NEEDS_CI }}
jobs:
  extension_build:
    runs-on: ubuntu-latest
    env:
      ON_CI: True
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - name: Installing npm dependencies
        run: |
          npm install -g typescript
          npm install -g vsce
          npm install
        working-directory: ./vscode_ext
      - name: Creating vsce package
        run: "vsce package --baseContentUrl https://github.com/open-needs/open-needs-ide --baseImagesUrl https://github.com/open-needs/open-needs-ide"
        working-directory: ./vscode_ext
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}s
      - name: Showing vs_code dir content
        working-directory: ./vscode_ext
        run: ls -la .
      - name: Storing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: open-needs-ide-nightly.vsix
          path: vscode_ext/open-needs-ide-*.vsix
          retention-days: 7
      - name: Releaseing on github releases
        # https://github.com/pyTooling/Actions/tree/main/releaser
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.OPEN_NEEDS_CI }}
          tag: nightly
          files: |
            vscode_ext/open-needs-ide-*.vsix